{% set version = "6.0.5" %}

package:
  name: multidict
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/multidict/multidict-{{ version }}.tar.gz
  sha256: f7e301075edaf50500f0b341543c41194d8df3ae5caf4702f2095f3ca73dd8da

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  commands:
    - py.test tests --no-c-extensions  # [python_impl != "cpython"]
    - py.test tests --c-extensions     # [python_impl == "cypthon"]
    - pip check

about:
  home: http://github.com/aio-libs/multidict
  license: Apache-2.0
  license_file: LICENSE
  summary: multidict implementation

  description: |
    Multidicts are useful for working with HTTP headers, URL query args etc.
  doc_url: http://multidict.readthedocs.io/
  dev_url: http://github.com/aio-libs/multidict

extra:
  recipe-maintainers:
    - sodre
    - kszucs
    - xhochy
